Algoritmo COMPARARDIJITOS 
	DEFINIR N,D1,D2,D3 COMO ENTERO
	ESCRIBIR "INGRESE UN NUMERO DE TRES CIFRAS ";
	LEER N;
	SI N >=100 Y N <1000 ENTONCES
		D1=N%10;
		D2=N%100;
		D2=TRUNC(DA/10)
		D2=TRUNC(DA/100)
		ESCRIBIR "U= "D1 " D= "D2" "=  cD3
	SiNo
		ESCRIBIR "FALSO";
		
	FinSi
	
	
FinAlgoritmo
