Algoritmo DATOS_PERSONALES
	DEFINIR NOMBRE, APELLIDO COMO CARACTER ;
	DEFINIR EDAD COMO CARACTER ;
	DEFINIR DATO COMO CARACTER
	ESCRIBIR"HOLA PORFAVOR INGRESA TU NOMBRE";
		LEER NOMBRE;
		ESCRIBIR "HOLA PORFAVOR INGRESA TU APELLIDO";
		LEER APELLIDO;
		ESCRIBIR "INGRESA TU EDAD ";
		LEER EDAD
		ESCRIBIR " HOLA "   NOMBRE,    APELLIDO, " GRACIAS POR DECIRME TU EDAD QUE A SIDO  "    EDAD "AÑOS";
	
FinAlgoritmo
