Algoritmo SUMAR2NUMEROS 
	DEFINIR NI,N2, R COMO ENTERO;
	ESCRIBIR "OYE PANA INGRESA NUMERO 1 ";
	LEER N1;
	ESCRIBIR "INGRESA EL NUMERO 2";
	LEER N2
	R= N1+N2;
	ESCRIBIR"LA SUMA ES=  :" R;
FinAlgoritmo
